"""initial schema

Revision ID: 8d2aabaf3840
Revises: 
Create Date: 2026-09-17 20:40:05.402954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8d2aabaf3840'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# degree_level, gpa_scale va deadline_type bir nechta jadvalda ishlatiladi
# (Program/User, ProgramRequirement/User, Deadline/ScholarshipDeadline).
# Postgres native enum turini har safar create_table'da qayta yaratishga
# urinmaslik uchun (bu "type already exists" xatosiga olib keladi) bitta
# marta qo'lda yaratamiz va column'larda create_type=False bilan ishlatamiz.
degree_level_enum = postgresql.ENUM("bachelor", "master", "phd", name="degree_level", create_type=False)
gpa_scale_enum = postgresql.ENUM("4", "5", "100", name="gpa_scale", create_type=False)
deadline_type_enum = postgresql.ENUM(
    "application_open", "application_close", "document", "visa",
    name="deadline_type", create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    degree_level_enum.create(bind, checkfirst=True)
    gpa_scale_enum.create(bind, checkfirst=True)
    deadline_type_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code')
    )
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coverage_type', sa.Enum('full', 'partial', 'contract_only', name='coverage_type'), nullable=False),
    sa.Column('coverage_percent', sa.Integer(), nullable=True),
    sa.Column('stipend_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('extras_flight', sa.Boolean(), nullable=False),
    sa.Column('extras_insurance', sa.Boolean(), nullable=False),
    sa.Column('extras_dormitory', sa.Boolean(), nullable=False),
    sa.Column('extras_language_course', sa.Boolean(), nullable=False),
    sa.Column('age_limit', sa.Integer(), nullable=True),
    sa.Column('citizenship_eligible', sa.Boolean(), nullable=False),
    sa.Column('university_choice', sa.Enum('assigned_by_scholarship', 'user_chooses', name='university_choice_type'), nullable=False),
    sa.Column('application_linked_to_program', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('ui_language', sa.Enum('uz', 'ru', 'en', name='ui_language'), nullable=False),
    sa.Column('gpa_raw', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gpa_scale', gpa_scale_enum, nullable=True),
    sa.Column('degree_level', degree_level_enum, nullable=True),
    sa.Column('major', sa.String(length=255), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('scholarship_deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('type', deadline_type_enum, nullable=False),
    sa.Column('date_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intake_term', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_language_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IELTS', 'TOEFL', 'DELE', 'TestDAF', 'other', name='language_cert_type'), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_other_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('GRE', 'GMAT', name='other_test_type'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_target_country',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'country_id')
    )
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('degree_level', degree_level_enum, nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=False),
    sa.Column('language_of_instruction', sa.String(length=100), nullable=False),
    sa.Column('duration_years', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('intake_term', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deadlines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('type', deadline_type_enum, nullable=False),
    sa.Column('date_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intake_term', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('tuition_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('visa_proof_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('living_cost_monthly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('last_checked', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id')
    )
    op.create_table('program_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('gpa_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gpa_scale', gpa_scale_enum, nullable=True),
    sa.Column('ielts_min', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('toefl_min', sa.Integer(), nullable=True),
    sa.Column('gre_required', sa.Boolean(), nullable=False),
    sa.Column('gre_min', sa.Integer(), nullable=True),
    sa.Column('prereq_major', sa.Text(), nullable=True),
    sa.Column('age_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id')
    )
    op.create_table('program_scholarship',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id', 'scholarship_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('scholarship_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'reviewed', 'resolved', name='report_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planning', 'applied', 'rejected', 'accepted', name='saved_program_status'), nullable=False),
    sa.Column('reminders_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'program_id', name='uq_saved_program')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_programs')
    op.drop_table('reports')
    op.drop_table('program_scholarship')
    op.drop_table('program_requirements')
    op.drop_table('program_costs')
    op.drop_table('deadlines')
    op.drop_table('programs')
    op.drop_table('user_target_country')
    op.drop_table('user_other_tests')
    op.drop_table('user_language_certificates')
    op.drop_table('universities')
    op.drop_table('scholarship_deadlines')
    op.drop_table('users')
    op.drop_table('scholarships')
    op.drop_table('countries')
    # ### end Alembic commands ###

    bind = op.get_bind()
    degree_level_enum.drop(bind, checkfirst=True)
    gpa_scale_enum.drop(bind, checkfirst=True)
    deadline_type_enum.drop(bind, checkfirst=True)
